var Tile;
(function (Tile) {
    Tile[Tile["DirtFloor"] = 0] = "DirtFloor";
    Tile[Tile["DirtWall"] = 1] = "DirtWall";
    Tile[Tile["DirtCorridor"] = 2] = "DirtCorridor";
    Tile[Tile["StoneFloor"] = 3] = "StoneFloor";
    Tile[Tile["StoneWall"] = 4] = "StoneWall";
    Tile[Tile["StoneDoor"] = 5] = "StoneDoor";
    Tile[Tile["WoodFloor"] = 6] = "WoodFloor";
    Tile[Tile["WoodWall"] = 7] = "WoodWall";
    Tile[Tile["WoodDoor"] = 8] = "WoodDoor";
    Tile[Tile["MetalFloor"] = 9] = "MetalFloor";
    Tile[Tile["MetalWall"] = 10] = "MetalWall";
    Tile[Tile["MetalDoor"] = 11] = "MetalDoor";
    Tile[Tile["WoodChest"] = 12] = "WoodChest";
    Tile[Tile["StoneChest"] = 13] = "StoneChest";
    Tile[Tile["MetalChest"] = 14] = "MetalChest";
    Tile[Tile["Upstairs"] = 15] = "Upstairs";
    Tile[Tile["Downstairs"] = 16] = "Downstairs";
    Tile[Tile["Empty"] = 17] = "Empty";
})(Tile || (Tile = {}));
exports.Tile = Tile;
